/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.view;

import ec.edu.ups.controller.VehiculoController;
import ec.edu.ups.model.Vehiculo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class ListaVehiculosView extends javax.swing.JFrame {
    
    private VehiculoController controller;

    public ListaVehiculosView(VehiculoController vehiculoController) {
        this.controller = vehiculoController;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 231));
        setPreferredSize(new java.awt.Dimension(537, 231));
        setResizable(false);
        setSize(new java.awt.Dimension(537, 231));
        getContentPane().setLayout(null);

        tablaVehiculos.setBackground(new java.awt.Color(204, 255, 255));
        tablaVehiculos.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tablaVehiculos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Placa", "Marca", "Modelo", "Año", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);
        if (tablaVehiculos.getColumnModel().getColumnCount() > 0) {
            tablaVehiculos.getColumnModel().getColumn(0).setResizable(false);
            tablaVehiculos.getColumnModel().getColumn(1).setResizable(false);
            tablaVehiculos.getColumnModel().getColumn(2).setResizable(false);
            tablaVehiculos.getColumnModel().getColumn(3).setResizable(false);
            tablaVehiculos.getColumnModel().getColumn(4).setResizable(false);
            tablaVehiculos.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 490, 100);

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("Salir");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(420, 20, 90, 24);

        lblSalir.setBackground(new java.awt.Color(255, 153, 102));
        lblSalir.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(0, 0, 0));
        lblSalir.setText("Listado de Vehiculos");
        lblSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        lblSalir.setOpaque(true);
        getContentPane().add(lblSalir);
        lblSalir.setBounds(20, 20, 310, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed
  private void cargarDatos() {
        List<Vehiculo> vehiculos = controller.obtenerVehiculos();
        DefaultTableModel model = (DefaultTableModel) tablaVehiculos.getModel();

        // Limpiar tabla existente
        model.setRowCount(0);

        for (Vehiculo vehiculo : vehiculos) {
            model.addRow(new Object[]{
                vehiculo.getPlaca(),
                vehiculo.getClass().getSimpleName(),
                vehiculo.getMarca(),
                vehiculo.getModelo(),
                vehiculo.getAño(),
                "$" + vehiculo.calcularCostoMatricula()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblSalir;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
