/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.view;

import ec.edu.ups.controller.VehiculoController;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class RegistrarVehiculoView extends javax.swing.JFrame {

    private VehiculoController controller;

    public RegistrarVehiculoView(VehiculoController vehiculoController) {
        this.controller = vehiculoController;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlaca = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JToggleButton();
        btnGuardar = new javax.swing.JToggleButton();
        txtMarca = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        JbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Vehiculo");
        setBackground(new java.awt.Color(153, 255, 204));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        txtPlaca.setBackground(new java.awt.Color(255, 255, 204));
        txtPlaca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(120, 60, 110, 23);

        txtAño.setBackground(new java.awt.Color(255, 255, 204));
        txtAño.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtAño);
        txtAño.setBounds(120, 190, 110, 23);

        txtModelo.setBackground(new java.awt.Color(255, 255, 204));
        txtModelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtModelo);
        txtModelo.setBounds(120, 150, 110, 23);

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setSelected(true);
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(270, 140, 95, 30);

        btnGuardar.setBackground(new java.awt.Color(153, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(270, 80, 95, 30);

        txtMarca.setBackground(new java.awt.Color(255, 255, 204));
        txtMarca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtMarca);
        txtMarca.setBounds(120, 110, 110, 23);

        lblTipo.setBackground(new java.awt.Color(204, 204, 255));
        lblTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo");
        lblTipo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblTipo.setMaximumSize(new java.awt.Dimension(28, 16));
        lblTipo.setMinimumSize(new java.awt.Dimension(28, 16));
        lblTipo.setOpaque(true);
        getContentPane().add(lblTipo);
        lblTipo.setBounds(30, 20, 70, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Marca");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 70, 20);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modelo");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 70, 20);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Año");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 190, 70, 20);

        lblPlaca.setBackground(new java.awt.Color(204, 204, 255));
        lblPlaca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca.setText("Placa");
        lblPlaca.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblPlaca.setMaximumSize(new java.awt.Dimension(28, 16));
        lblPlaca.setMinimumSize(new java.awt.Dimension(28, 16));
        lblPlaca.setOpaque(true);
        getContentPane().add(lblPlaca);
        lblPlaca.setBounds(30, 60, 70, 20);

        JbTipo.setBackground(new java.awt.Color(255, 255, 204));
        JbTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JbTipo.setForeground(new java.awt.Color(0, 0, 0));
        JbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto", "camioneta", "camion" }));
        JbTipo.setMinimumSize(new java.awt.Dimension(15, 25));
        JbTipo.setPreferredSize(new java.awt.Dimension(15, 25));
        JbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(JbTipo);
        JbTipo.setBounds(120, 20, 110, 26);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//         String tipo = txtTipo.getText().trim();
        String tipo = JbTipo.getSelectedItem().toString();
        String placa = txtPlaca.getText().trim();
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String añoStr = txtAño.getText().trim();
        
               if (tipo.isEmpty() || placa.isEmpty() || marca.isEmpty() || modelo.isEmpty() || añoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int año;
        try {
            año = Integer.parseInt(añoStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un año válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double costo  = controller.registrarVehiculo(tipo, placa, marca, modelo, año);
        if (costo != -1) {
            JOptionPane.showMessageDialog(this, "Vehículo registrado correctamente.\nCosto de matrícula: $" + costo, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();  
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de vehículo no válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void JbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JbTipo;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
